### ISSUE TITLE
Detect unkonwn CLI arguments

### ISSUE THREAD

**Issue by davazp** [ams-hackers/delisp#63]
To reproduce it:

`npx delisp compile --unknown-arg`

**Comment by tkers** [comment]
This seems to be already correctly handled? Or is this about ignoring extra arguments?

Both on the published package and on master the CLI fails with  **Unknown argument: unknown**

```
delisp compile [files...]

Compile delisp files

Options:
  --version         Show version number                                [boolean]
  --color                                                              [boolean]
  --help            Show help                                          [boolean]
  --module          Module format to use[choices: "cjs", "esm"] [default: "cjs"]
  --ts-declaration  Generate Typescript declaration file               [boolean]

Unknown argument: unknown
```

**Comment by davazp** [comment]
I over-simplified the issue it seems.

`delisp compile --ts-de init.dl`

or anything else containing `-` gives the following error.  If the argument doesn't contain `-` then it is properly detected as unknown.

```
/Users/davazp/Projects/delisp/packages/delisp/node_modules/yargs/yargs.js:1163
      else throw err
           ^

TypeError: Cannot read property 'map' of undefined
    at Object.handler (/Users/davazp/Projects/delisp/packages/delisp/dist/src/cmd-compile.js:59:27)
    at Object.runCommand (/Users/davazp/Projects/delisp/packages/delisp/node_modules/yargs/lib/command.js:242:26)
    at Object.parseArgs [as _parseArgs] (/Users/davazp/Projects/delisp/packages/delisp/node_modules/yargs/yargs.js:1078:30)
    at Object.get [as argv] (/Users/davazp/Projects/delisp/packages/delisp/node_modules/yargs/yargs.js:1012:21)
    at Object.<anonymous> (/Users/davazp/Projects/delisp/packages/delisp/dist/src/index.js:24:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

**Comment by davazp** [comment]
Strange, it seems to be a problem in `yargs`.

**Comment by davazp** [comment]
I reported it in the yargs repository:
https://github.com/yargs/yargs/issues/1325
